import { assetUrl } from '../lib/assetUrl'

export const assets = {
  background: assetUrl('assets/фон.png'),
  headerLogo: assetUrl('assets/header-logo.png'),
  finaleCat: assetUrl('assets/finale-cat.png'),
  legendCat: assetUrl('assets/legend-cat.png'),
  legendCloud: assetUrl('assets/legend-cloud.png'),
  iconMcbs: assetUrl('assets/icon-mcbs.png'),
  iconVk: assetUrl('assets/icon-vk.png'),
  audio: {
    'cp-1': assetUrl('audio/part-01-cp-1-library.mp3'),
    'transit-1-2': assetUrl('audio/part-02-transit-1-2.mp3'),
    'cp-2': assetUrl('audio/part-03-cp-2-mendeleev.mp3'),
    'cp-3': assetUrl('audio/part-04-cp-3-angel.mp3'),
    'transit-3-4': assetUrl('audio/part-05-transit-3-4.mp3'),
    'cp-4': assetUrl('audio/part-06-cp-4-invisible.mp3'),
    'cp-5': assetUrl('audio/part-07-cp-5-egyptian.mp3'),
    'transit-5-6': assetUrl('audio/part-08-transit-5-6.mp3'),
    'cp-6': assetUrl('audio/part-09-cp-6-semimostye.mp3'),
    'cp-7': assetUrl('audio/part-10-cp-7-naval-cathedral.mp3'),
    'transit-7-8': assetUrl('audio/part-11-transit-7-8.mp3'),
    'cp-8': assetUrl('audio/part-12-cp-8-lion-bridge.mp3'),
    'cp-9': assetUrl('audio/part-13-cp-9-srednyaya.mp3'),
    'cp-10': assetUrl('audio/part-14-cp-10-brinko.mp3'),
    'cp-11': assetUrl('audio/part-15-cp-11-hauptwachte.mp3'),
    finale: assetUrl('audio/part-16-finale.mp3'),
  },
  placeAudio: {
    pomeshchik: assetUrl('audio/cards/card-01-pomeshchik.mp3'),
    mendeleev: assetUrl('audio/cards/card-02-mendeleev.mp3'),
    garnovsky: assetUrl('audio/cards/card-03-garnovsky.mp3'),
    invisible_man: assetUrl('audio/cards/card-04-invisible.mp3'),
    egyptian_bridge: assetUrl('audio/cards/card-05-egyptian.mp3'),
    semimostye: assetUrl('audio/cards/card-06-semimostye.mp3'),
    naval_cathedral: assetUrl('audio/cards/card-07-naval-cathedral.mp3'),
    litovsky_castle: assetUrl('audio/cards/card-08-litovsky.mp3'),
    srednyaya_podyacheskaya: assetUrl('audio/cards/card-09-srednyaya.mp3'),
    brinko: assetUrl('audio/cards/card-10-senna-brinko.mp3'),
  },
  mapSegments: {
    '1-2': assetUrl('assets/maps/map-1-2.png'),
    '2-3': assetUrl('assets/maps/map-2-3.png'),
    '3-4': assetUrl('assets/maps/map-3-4.png'),
    '4-5': assetUrl('assets/maps/map-4-5.png'),
    '5-6': assetUrl('assets/maps/map-5-6.png'),
    '6-7': assetUrl('assets/maps/map-6-7.png'),
    '7-8': assetUrl('assets/maps/map-7-8.png'),
    '8-9': assetUrl('assets/maps/map-8-9.png'),
    '9-10': assetUrl('assets/maps/map-9-10.png'),
    '10-11': assetUrl('assets/maps/map-10-11.png'),
  },
  locations: {
    library: assetUrl('assets/locations/01-library.jpg'),
    mendeleev: assetUrl('assets/locations/02-mendeleev.jpg'),
    angel: assetUrl('assets/locations/03-angel.jpg'),
    invisibleMan: assetUrl('assets/locations/04-invisible.jpg'),
    egyptian: assetUrl('assets/locations/05-egyptian.jpg'),
    semimostye: assetUrl('assets/locations/06-semimostye.jpg'),
    navalCathedral: assetUrl('assets/locations/07-naval-cathedral.jpg'),
    lionBridge: assetUrl('assets/locations/08-lion-bridge.jpg'),
    srednyaya: assetUrl('assets/locations/09-srednyaya.jpg'),
    brinko: assetUrl('assets/locations/10-brinko.jpg'),
    hauptwachte: assetUrl('assets/locations/11-hauptwachte.jpg'),
  },
  photos: {
    pomeshchik: assetUrl('assets/photos/pomeshchik.jpg'),
    labzin: assetUrl('assets/photos/labzin.jpg'),
    mendeleev: assetUrl('assets/photos/mendeleev-card.jpg'),
    invisibleMain: assetUrl('assets/photos/invisible-main.jpg'),
    invisibleHistoric: assetUrl('assets/photos/invisible-historic.png'),
    egyptianMain: assetUrl('assets/photos/egyptian-card.jpg'),
    egyptianCollapse: assetUrl('assets/photos/egyptian-collapse.jpg'),
    semimostye: assetUrl('assets/photos/semimostye-card.jpg'),
    navalCathedral: assetUrl('assets/photos/naval-cathedral-card.jpg'),
    litovskyFacade: assetUrl('assets/photos/litovsky-facade.jpg'),
    litovskyBurned: assetUrl('assets/photos/litovsky-burned.jpg'),
    garnovsky: assetUrl('assets/photos/garnovsky.jpg'),
    srednyaya: assetUrl('assets/photos/srednyaya-card.jpg'),
    sennaMarket: assetUrl('assets/photos/senna-market.jpg'),
    sennaView: assetUrl('assets/photos/senna-view.jpg'),
  },
} as const
